//
// Created by roy on 13/01/19.
//

#ifndef ROYANDIDANPROJECT2_SERVERCOMMUNICATION_H
#define ROYANDIDANPROJECT2_SERVERCOMMUNICATION_H


class ServerCommunication {

};


#endif //ROYANDIDANPROJECT2_SERVERCOMMUNICATION_H
